### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by huutho-dev** [jonataslaw/get_server#29] opened 2020-12-30 03:43 UTC
![image](https://user-images.githubusercontent.com/14016488/103328449-8bb90480-4a8b-11eb-88f0-1018be3857b1.png)

Server crashed when running pageable

**Comment by huutho-dev** [comment] 2020-12-30 03:45
![image](https://user-images.githubusercontent.com/14016488/103328563-ed796e80-4a8b-11eb-86ad-8b60af72d3c7.png)
Comments like above image will work

(Sr my bad English)

**Comment by Katekko** [comment] 2020-12-30 22:51
Can you pass the full example so I can reproduce my self here.

**Comment by huutho-dev** [comment] 2020-12-31 02:10
> Can you pass the full example so I can reproduce my self here.

I run the code at the branch master
https://github.com/jonataslaw/get_server
http://localhost:8080/pageable

**Comment by jonataslaw** [comment] 2021-07-27 01:05
I can't reproduce this in the latest version, so closing this

**Closed by jonataslaw** 2021-07-27 01:05 UTC
